#!/usr/bin/env python3
"""把最新 HTML 与 API 快照打包为无依赖 Cloudflare Worker。"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def js_literal(value):
    return json.dumps(value, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--project-root", required=True)
    args = parser.parse_args()
    root = Path(args.project_root).resolve()

    dashboard_html = (root / "dashboard.html").read_text(encoding="utf-8")
    api_payload = json.loads((root / "data" / "dashboard_api.json").read_text(encoding="utf-8"))
    output = root / "worker" / "index.js"
    output.parent.mkdir(parents=True, exist_ok=True)

    source_urls = [
        {"source_id": row["source_id"], "name": row["name"], "url": row["url"]}
        for row in api_payload["sources"]
    ]

    worker = f"""// Generated by scripts/build_online_worker.py. Do not edit directly.
const DASHBOARD = {js_literal(api_payload)};
const DASHBOARD_HTML = {js_literal(dashboard_html)};
const SOURCE_URLS = {js_literal(source_urls)};

const HEADERS = {{
  "content-type": "application/json; charset=utf-8",
  "access-control-allow-origin": "*",
  "access-control-allow-methods": "GET, OPTIONS",
  "x-content-type-options": "nosniff"
}};

function jsonResponse(value, status = 200, extra = {{}}) {{
  return new Response(JSON.stringify(value), {{
    status,
    headers: {{...HEADERS, "cache-control": "public, max-age=300", ...extra}}
  }});
}}

async function checkSource(source) {{
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), 6000);
  const checkedAt = new Date().toISOString();
  try {{
    let response = await fetch(source.url, {{
      method: "GET",
      headers: {{"user-agent": "LLM-Market-Monitor/1.0", "accept": "text/html,*/*"}},
      redirect: "follow",
      signal: controller.signal
    }});
    clearTimeout(timer);
    return {{
      ...source,
      checked_at: checkedAt,
      ok: response.ok,
      http_status: response.status,
      final_url: response.url
    }};
  }} catch (error) {{
    clearTimeout(timer);
    return {{
      ...source,
      checked_at: checkedAt,
      ok: false,
      http_status: null,
      error: error instanceof Error ? error.message : String(error)
    }};
  }}
}}

async function liveSourceHealth() {{
  const rows = await Promise.all(SOURCE_URLS.map(checkSource));
  return {{
    checked_at: new Date().toISOString(),
    successful: rows.filter(row => row.ok).length,
    total: rows.length,
    rows
  }};
}}

export default {{
  async fetch(request) {{
    const url = new URL(request.url);
    if (request.method === "OPTIONS") return new Response(null, {{status: 204, headers: HEADERS}});
    if (request.method !== "GET") return jsonResponse({{error: "method_not_allowed"}}, 405);

    if (url.pathname === "/" || url.pathname === "/index.html") {{
      return new Response(DASHBOARD_HTML, {{
        headers: {{
          "content-type": "text/html; charset=utf-8",
          "cache-control": "public, max-age=300",
          "x-content-type-options": "nosniff",
          "content-security-policy": "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; base-uri 'none'; frame-ancestors 'self'"
        }}
      }});
    }}
    if (url.pathname === "/api" || url.pathname === "/api/") {{
      return jsonResponse({{
        name: "LLM Token Economy Monitor API",
        snapshot_at: DASHBOARD.meta.generated_at,
        endpoints: [
          "/api/dashboard", "/api/pricing", "/api/business", "/api/tokens",
          "/api/sources", "/api/signals", "/api/history", "/api/live/sources", "/health"
        ]
      }});
    }}
    if (url.pathname === "/api/dashboard") return jsonResponse(DASHBOARD);
    if (url.pathname === "/api/pricing") return jsonResponse({{meta: DASHBOARD.meta, rows: DASHBOARD.pricing}});
    if (url.pathname === "/api/business") return jsonResponse({{meta: DASHBOARD.meta, rows: DASHBOARD.business}});
    if (url.pathname === "/api/tokens") return jsonResponse({{meta: DASHBOARD.meta, rows: DASHBOARD.tokens}});
    if (url.pathname === "/api/sources") return jsonResponse({{meta: DASHBOARD.meta, rows: DASHBOARD.sources}});
    if (url.pathname === "/api/signals") return jsonResponse({{meta: DASHBOARD.meta, rows: DASHBOARD.signals}});
    if (url.pathname === "/api/history") return jsonResponse({{meta: DASHBOARD.meta, series: DASHBOARD.history_series}});
    if (url.pathname === "/api/live/sources") return jsonResponse(await liveSourceHealth(), 200, {{"cache-control": "no-store"}});
    if (url.pathname === "/health") {{
      return jsonResponse({{
        status: "ok",
        snapshot_at: DASHBOARD.meta.generated_at,
        metrics_as_of: DASHBOARD.meta.metrics_as_of,
        source_success: DASHBOARD.kpis.source_success
      }}, 200, {{"cache-control": "no-store"}});
    }}
    return jsonResponse({{error: "not_found", path: url.pathname}}, 404);
  }}
}};
"""
    output.write_text(worker, encoding="utf-8", newline="\n")
    print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
